version: '2'

services:
  postgres:
    image: santanarscs/postgresql
    container_name: eacademico-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=eacademico
      - POSTGRES_DB=eacademico
      - POSTGRES_USER=eacademico
  oracle:
    image: santanarscs/oracle-express
    container_name: eacademico-oracle
    ports:
      - "1521:1521"
  wildfly:
    image: santanarscs/wildfly
    container_name: eacademico-wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    depends_on:
      - oracle
    links:
      - oracle
  tomcat:
    image: santanarscs/tomcat
    container_name: eacademico-tomcat
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    links:
      - postgres
  nuxeo:
    image: santanarscs/nuxeo
    container_name: eacademico-nuxeo
    ports:
      - "8085:8080"
  swagger:
    image: santanarscs/swagger
    container_name: eacademico-swagger
    ports:
      - "8086:8080"
