CREATE USER SIG IDENTIFIED BY SIG;
 
 GRANT CONNECT TO SIG;
 
 GRANT CONNECT, RESOURCE, DBA TO SIG;
 
 GRANT UNLIMITED TABLESPACE TO SIG;
 
 COMMIT;
 
 CREATE TABLE "SIG"."VW_PESSOAS_TODAS"
  (    "NR_ORDEM" VARCHAR2(255 CHAR),
    "NR_CPF" VARCHAR2(255 CHAR),
    "DT_NASCIMENTO" TIMESTAMP (6),
    "SG_ESPECIALIDADE" VARCHAR2(255 CHAR),
    "NM_COMPLETO" VARCHAR2(255 CHAR),
    "NM_GUERRA" VARCHAR2(255 CHAR),
    "CD_OM" VARCHAR2(255 CHAR),
    "SG_POSTO" VARCHAR2(255 CHAR),
    "SG_QUADRO" VARCHAR2(255 CHAR),
    "SG_SEXO" VARCHAR2(255 CHAR)
  );
 
  COMMIT;
 
  CREATE TABLE "SIG"."VW_ORGANIZACOES_TODAS"
  (    "NR_ORDEM" VARCHAR2(255 CHAR),
    "NR_CPF" VARCHAR2(255 CHAR),
    "DT_NASCIMENTO" TIMESTAMP (6),
    "SG_ESPECIALIDADE" VARCHAR2(255 CHAR),
    "NM_COMPLETO" VARCHAR2(255 CHAR),
    "NM_GUERRA" VARCHAR2(255 CHAR),
    "CD_OM" VARCHAR2(255 CHAR),
    "SG_POSTO" VARCHAR2(255 CHAR),
    "SG_QUADRO" VARCHAR2(255 CHAR),
    "SG_SEXO" VARCHAR2(255 CHAR)
  );
 
  COMMIT;
